version: '2'
services:
  elasticsearch:
    build: .
    volumes:
      - ./es_data/:/usr/share/elasticsearch/data/
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
  kibana:
    build: kibana
    links:
      - elasticsearch
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
